language: node_js
node_js:
  - "12.14.1"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
before_deploy:
  - tar cvzf stepping-stone.tar.gz build/
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build
    on:
      branch: master
  - provider: releases
    api_key: $github_token
    file:
      - stepping-stone.tar.gz
    skip_cleanup: true
    on:
      tags: true
